apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: wordpress-app
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      args:
        - "--ignore-db-dir=lost+found"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql
      persistentVolumeClaim:
        claimName: mysqlpvc


