apiVersion: v1
kind: Service
metadata:
  name: mysql_service
  labels:
    name: mysql_service
    app: wordpress_app
spec:
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    matchLabels:
      name: mysql
  type: CLusterIP


