apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: wordpress_app
spec:
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    name: mysql
  type: ClusterIP


