apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
  labels:
    name: mysqlpv
    app: wordpress-app
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
  volumeMode: Filesystem

