apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql_pv
  labels:
    name: mysql_pv
    app: wordpress_app
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
  volumeMode: Filesystem

