apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mysql_pvc
    app: wordpress_app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: mysql_pv
      app: wordpress_app



