apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  labels:
    name: mysqlpvc
    app: wordpress-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: mysqlpv
      app: wordpress-app



