apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    name: wordpress
    app: wordpress-app
spec:
  containers:
    - name: wordpress
      image: wordpress
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER=
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
      ports:
        - containerPort: 80
