apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    name: wordpress-service
    app: wordpress-app
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: wordpress
  type: LoadBalancer