apiVersion: v1
kind: Pod
metadata:
  labels:
    name: wordpress
    app: wordpress_app
spec:
  containers:
    - name: wordpress
      image: wordpress
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql_service
        - name: WORDPRESS_DB_USER=
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
      ports:
        containerPort: 80
