apiVersion: v1
kind: Service
metadata:
  name: wordpress_service
  labels:
    name: wordpress_service
    app: wordpress_app
spec:
  ports:
    targetPort: 80
    port: 80
  selector:
    matchLabels:
      name: wordpress
      app: wordpress_app
  type: LoadBalancer